area/github-management:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/**"

area/documentation:
  - changed-files:
      - any-glob-to-any-file:
          - "docs/*.md"
          - "docs/*.txt"

area/profile:
  - changed-files:
      - any-glob-to-any-file:
          - "profile/**"
